import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
// import { ThemeModeScript } from 'flowbite-react';
import Footer from '@/components/common/footer';
const inter = Inter({ subsets: ['latin'] });
import Providers from './providers';
// import { initDB } from '@/lib/sequelize';
import { initDatabase } from '@/lib/db';

export async function generateMetadata() {
  // await SequelizeDB.authenticate({});
  // await SequelizeDB.sync({
  //   force: false,
  //   alter: true,
  // });
  await initDatabase();
  

  return {
    title: 'Create Next App',
    description: 'Generated by create next app',
  };
}
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };
import Notification from '@/components/common/dialogs/notification';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>{/* <ThemeModeScript /> */}</head>
      <body className={`${inter.className}`}>
        <Providers>
          <Notification />

          {children}
        </Providers>
      </body>
    </html>
  );
}
