import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Footer from '@/components/common/footer';
const inter = Inter({ subsets: ['latin'] });
import Providers from './providers';
import IdDialog from '@/components/common/dialogs/id-dialog';
import MDAService from '@/services/mda-service';
import logo  from '/public/images.jpeg';
export async function generateMetadata() {
  // await MDAService.createBulkMDA();
  // console.log(process.env.GMAIL_PASSWORD); 

  return {
    title:
      'Income, Assets & Liabilities Declaration, Anti-Corruption Commission, Republic of Sierra Leone',
    description:
      'Income, Assets & Liabilities Declaration, Anti-Corruption Commission, Republic of Sierra Leone',
  };
}
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-blue-gray-50/50 `}
      
      >
        <Providers>
          <IdDialog />

          {/* <Notification /> */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
